//! This library provides types and functions which are used by the Rust code generated by
//! [`naga_rust_back`] or [`naga_rust_embed`]. These types and functions implement vector arithmetic
//! in the style expected by shader code, which differs from straightforward Rust in various ways.
//!
//! This library currently does not have a clean public API distinct from the API provided
//! for the benefit of the code generator. Expect changes in future versions.
//!
//! [`naga_rust_back`]: https://docs.rs/naga-rust-back
//! [`naga_rust_embed`]: https://docs.rs/naga-rust-embed

#![no_std]

#[cfg(feature = "alloc")]
extern crate alloc;
#[cfg(feature = "std")]
extern crate std;

mod matrix;
pub mod texture;
mod vector;

// -------------------------------------------------------------------------------------------------

pub use matrix::*;
pub use texture::{
    Sampler, Texture1d, Texture2d, Texture2dArray, Texture3d, TextureCube, TextureCubeArray,
    TextureMultisampled2d,
};
pub use vector::*;

// Traits the generated code refers to
pub use core::convert::Into;
pub use core::default::Default;

// -------------------------------------------------------------------------------------------------

/// Returns the [WGSL zero value] of a type.
///
/// Conveniently, all of the types for which this is defined also implement [`Default`] to return
/// zero, so this is actually an alias for [`Default::default()`].
///
/// [WGSL zero value]: https://www.w3.org/TR/2026/CRD-WGSL-20260507/#zero-value
pub fn zero<T: Default>() -> T {
    Default::default()
}

pub fn discard() {
    // Best we can do for now, until we implement a codegen option to return Result instead.
    panic!("shader reached discard instruction");
}

// Attributes which naga_rust_back emits that are currently for documentation purposes only,
// and don’t actually transform the item.
pub use naga_rust_macros::dummy_attribute as compute;
pub use naga_rust_macros::dummy_attribute as fragment;
pub use naga_rust_macros::dummy_attribute as vertex;
pub use naga_rust_macros::dummy_attribute as workgroup_size;
