[package]
name = "compile-tests"
edition = "2024"
publish = false

[build-dependencies]
naga-rust = { workspace = true }
naga = { workspace = true, features = ["wgsl-in"] }

[dependencies]
naga-rust-rt = { workspace = true }

[lints]
workspace = true
